# modules configuration file

# Shared twitter keys that can be applied to twittersearch, twitterstream
# modules can be specified as below. These are default values unless explicit values are
# set for module config keys in the respective twitter(search/stream) source modules.

# Uncomment and set the below to activate properties that are applied to all twitter sources
#twitter:
#  consumerKey: fooconsumer123
#  consumerSecret: fooconsumersecretABC
#  accessToken: 123456789-fooaccesstoken
#  accessTokenSecret: fooaccesstokensecret
#
# Once the above properties are set, the twitterstream/twittersearch source modules will use
# them by default.
# To override these properties:
# Remove the shared property keys and set explicit property values in source/<module>/twitter(stream/search).properties
# For example, in source/twittersearch/twittersearch.properties:
#  consumerKey=mynewConsumerKey
#  consumerSecret=overriddingSecret123
#
# Other source/processor/sink/job modules' properties can be configured in a similar way
# Rabbit source/sink module configuration is one other example below.

---

# Shared RabbitMQ module properties
#
# The default values for rabbit modules are taken from spring.rabbitmq.addresses and related 
# variables defined in servers.yml
#
# If you uncomment this section, you should also uncomment related lines in 
#   - XD_HOME/xd/config/modules/source/rabbit/rabbit.properties
#   - XD_HOME/xd/config/modules/sink/rabbit/rabbit.properties
#
#  NOTE: sslProperties is mutually exclusive with keyStore, keyStorePassphrase, trustStore, trustStorePassphrase.
#  if you set inline properties, values in the properties file location given by 'sslProperties' will be ignored.
#
#rabbit:
#  addresses: localhost:5672
#  username: guest
#  password: guest
#  vhost: /
#  useSSL: false
#  sslProperties:
#  ssl:
#    keyStore:
#    keyStorePassphrase:
#    trustStore:
#    trustStorePassphrase:

---

#Connection Pool Settings
#spring:
#  datasource:
#    testOnBorrow: true
#    validationInterval: 30000
#    maxActive: 100
#    maxIdle: 100
#    minIdle: 10
#    initialSize: 0
#    maxWait: 30000
#    testOnReturn: false
#    testWhileIdle: false
#    timeBetweenEvictionRunsMillis: 5000
#    minEvictableIdleTimeMillis: 60000
#    removeAbandoned: false
#    removeAbandonedTimeout: 60
#    logAbandoned: false
#Tomcat JDBC Enhanced Attributes
#    jmxEnabled: true
#    fairQueue: true
#    abandonWhenPercentageFull: 0
#    maxAge: 0
#    useEquals: true
#    suspectTimeout: 0
#    alternateUsernameAllowed: false

---

#Kafka module properties
#kafka:
#  zkconnect: localhost:2181/xd-kafkasource

---

#Gemfire module properties
#
# host and port may each be comma-delimited values or single values. If both are comma-delimited values they will be
# applied pair-wise in list order. The following is equivalent to localhost[10334],localhost[10335]
#
#gemfire:
#   useLocator: true
#   host: localhost
#   port: 10334,10335

---
